ARG BASE_IMAGE=registry.access.redhat.com/ubi9-minimal
FROM $BASE_IMAGE
ARG BUILD_DIR=.
LABEL \
  org.opencontainers.image.title="Skupper Network Console Collector" \
  org.opencontainers.image.description="Exposes Skupper network details thorugh an API, metrics and a web console"

# Create user and group and switch to user's context
RUN useradd --uid 10000 runner
USER 10000

WORKDIR /app
COPY --chown=10000:10000 $BUILD_DIR/network-console-collector .
ADD --chown=10000:10000 ./dist/web/console.tar.gz ./console
ENTRYPOINT ["/app/network-console-collector"]
