ARG BASE_IMAGE=registry.access.redhat.com/ubi9-minimal
FROM $BASE_IMAGE
ARG BUILD_DIR=.
LABEL \
  org.opencontainers.image.title="Skupper Bootstrap" \
  org.opencontainers.image.description="Produces and manges static configurations for non-kube installations of Skupper"

# Create user and group and switch to user's context
RUN useradd --uid 10000 runner
USER 10000

WORKDIR /app
COPY --chown=10000:10000 $BUILD_DIR/bootstrap  .
CMD ["/app/bootstrap"]
