version: 2.1
orbs:
    docker: circleci/docker@1.0.1
    kube-orb: circleci/kubernetes@0.11.0
    go: circleci/go@1.7.1

executors:
  image_builder:
    resource_class: large
    machine:
      image: ubuntu-2204:2022.10.2

yaml-templates:
  branch_filters: &run_for_all_branches_and_numeric_tags
    filters:
      tags:
        only: /[0-9].*/

workflows:
  version: 2.1
  build-workflow:
    jobs:
      - build_and_save_test_images:
          <<: *run_for_all_branches_and_numeric_tags


commands:
  local_registry_start:
    description: prepare a local registry
    steps:
      - run:
          name: defining insecure registry location
          command: |
            echo "{\"insecure-registries\": [\"0.0.0.0:5000\"]}" | jq > /tmp/daemon.json
            sudo cp /tmp/daemon.json /etc/docker/
            sudo systemctl restart docker
      - run:
          name: create registry container
          command: |
            docker run --name registry -d -p 5000:5000 registry

jobs:
  build_and_save_test_images:
    executor: image_builder
    steps:
      - local_registry_start
      - checkout
      - run: docker buildx create --use --name skupper-buildx
      - run: make -e docker-build CACHE_REGISTRY=127.0.0.1:5000
      - run:
          name: persisting images to workspace
          command: |
            mkdir /tmp/images
            docker tag quay.io/skupper/service-controller 0.0.0.0:5000/service-controller
            docker save 0.0.0.0:5000/service-controller | gzip > /tmp/images/service-controller.gz
            docker tag quay.io/skupper/controller-podman 0.0.0.0:5000/controller-podman
            docker save 0.0.0.0:5000/controller-podman | gzip > /tmp/images/controller-podman.gz
            docker tag quay.io/skupper/config-sync 0.0.0.0:5000/config-sync
            docker save 0.0.0.0:5000/config-sync | gzip > /tmp/images/config-sync.gz
            docker tag quay.io/skupper/flow-collector 0.0.0.0:5000/flow-collector
            docker save 0.0.0.0:5000/flow-collector | gzip > /tmp/images/flow-collector.gz
            docker tag quay.io/skupper/skupper-tests 0.0.0.0:5000/skupper-tests
            docker save 0.0.0.0:5000/skupper-tests | gzip > /tmp/images/test-image.gz
      - persist_to_workspace:
          root: /tmp
          paths:
            - images/
